
import time
print("After many more days of running, right when you are about to collapse,")
print("you see a house with people gesturing to you to go in.")
time. sleep(10)
print("The men look at you and ask,")
time. sleep(3.5)
print("Are you the one who escaped?")
time. sleep(3.5)
print("You nod, reluctantly.")
time. sleep(2)
print("They take you into the house, and you learn that they were also trying to find the alliance.")
time. sleep(7)
print("The house was a calculation office that they took over.")
time. sleep(4)
print("And with that, you start working.")
time. sleep(2.5)
print("A building is being constructed next to the office,")
print("so many of the questions are for the area of circles.")
time. sleep(10)
print("The men also like to place bets, so you need to roll dice.")
time. sleep(6)
print("The job starts off well, with you in the basement inputting calculations.")
time. sleep(7)
